### ISSUE TITLE
Token error

### ISSUE THREAD

**Issue by vosmike** [homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#627]
Does the token change after a given time?
I havent changed my token but the plugin stopped working where it worked flawless before.
Is it firmware related maybe? I’m running the latest.

The error:
HOOBS4 ERROR[Model=unknown] ERR connect | miio.device, next try in 2 minutes | Error: Could not connect to device, token might be wrong

any other way to extract the token on a Mac?

**Comment by afharo** [comment]
> Does the token change after a given time?

AFAIK, It shouldn't change on its own (unless Xiaomi thinks is needed or you pair your robot with other apps like the Roborock app). The token might also change when resetting the robot or reconnecting it to the WiFi.

Another issue I've seen in the past: the router assigned a new IP to the robot. Can you validate it hasn't changed?

Finally, the original `miio` library (the underlying connection to send the commands to the robot) sometimes gets into a weird state that can only be solved via restarts. I managed to reduce how often it happens to a minimum, but it may still occur from time to time (which is super hard to debug and troubleshoot ☹️).

> any other way to extract the token on a Mac?

My preferred method is https://github.com/PiotrMachowski/Xiaomi-cloud-tokens-extractor. It removes all the backup-extract-decrypt nonsense.

**Comment by vosmike** [comment]
> > Does the token change after a given time?
> 
> AFAIK, It shouldn't change on its own (unless Xiaomi thinks is needed or you pair your robot with other apps like the Roborock app). The token might also change when resetting the robot or reconnecting it to the WiFi.
> 
> Another issue I've seen in the past: the router assigned a new IP to the robot. Can you validate it hasn't changed?
> 
> Finally, the original `miio` library (the underlying connection to send the commands to the robot) sometimes gets into a weird state that can only be solved via restarts. I managed to reduce how often it happens to a minimum, but it may still occur from time to time (which is super hard to debug and troubleshoot ☹️).
> 
> > any other way to extract the token on a Mac?
> 
> My preferred method is https://github.com/PiotrMachowski/Xiaomi-cloud-tokens-extractor. It removes all the backup-extract-decrypt nonsense.

Thanks! I checked the IP already, but that was still the same. Somehow I got different tokens from the backup compared to your method. The token from your method is now working! All fixed for me, thanks!
